/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import main.Conexion;

/**
 *
 * @author User
 */
public class frmRegistro extends javax.swing.JFrame {
    
    /**
     * Creates new form frmRegistro
     */
    public frmRegistro() {
        initComponents();
        setLocationRelativeTo(null);
        rootPane.setDefaultButton(btnRegistrar2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtConfirmarContraseña2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtContraseña2 = new javax.swing.JTextField();
        txtNombre2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnRegistrar2 = new javax.swing.JButton();
        btnInicia = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnMenuPrincipal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1367, 768));
        setSize(new java.awt.Dimension(1291, 662));
        getContentPane().setLayout(null);

        txtUser2.setBackground(new java.awt.Color(0, 0, 0));
        txtUser2.setForeground(new java.awt.Color(255, 255, 255));
        txtUser2.setToolTipText("Ingrese su nombre de usuario");
        getContentPane().add(txtUser2);
        txtUser2.setBounds(100, 240, 220, 40);

        jLabel11.setText("Usuario:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(47, 109, 79, 18);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setText("Worksy");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(261, 36, 116, 44);

        jLabel12.setText("Contraseña:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(371, 112, 56, 13);

        txtConfirmarContraseña2.setBackground(new java.awt.Color(0, 0, 0));
        txtConfirmarContraseña2.setForeground(new java.awt.Color(255, 255, 255));
        txtConfirmarContraseña2.setToolTipText("Ingrese su nombre de usuario");
        getContentPane().add(txtConfirmarContraseña2);
        txtConfirmarContraseña2.setBounds(500, 240, 230, 40);

        jLabel13.setText("Confirmar Contraseña:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(371, 214, 125, 13);

        txtContraseña2.setBackground(new java.awt.Color(0, 0, 0));
        txtContraseña2.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña2.setToolTipText("Ingrese su nombre de usuario");
        txtContraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña2);
        txtContraseña2.setBounds(500, 450, 240, 40);

        txtNombre2.setBackground(new java.awt.Color(0, 0, 0));
        txtNombre2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtNombre2);
        txtNombre2.setBounds(100, 450, 220, 40);

        jLabel15.setText("Nombre:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(47, 214, 40, 13);

        btnCancelar.setToolTipText("Cierra la aplicación");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(390, 633, 180, 40);

        btnRegistrar2.setBorderPainted(false);
        btnRegistrar2.setContentAreaFilled(false);
        btnRegistrar2.setFocusPainted(false);
        btnRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar2);
        btnRegistrar2.setBounds(687, 633, 190, 40);

        btnInicia.setToolTipText("");
        btnInicia.setContentAreaFilled(false);
        btnInicia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicia);
        btnInicia.setBounds(80, 634, 180, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(100, 150, 780, 10);

        btnMenuPrincipal.setBorderPainted(false);
        btnMenuPrincipal.setContentAreaFilled(false);
        btnMenuPrincipal.setFocusPainted(false);
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuPrincipal);
        btnMenuPrincipal.setBounds(60, 40, 180, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sitio web tecnológico con formas 3d fondo negro (7).png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        Conexion conexion = new Conexion();
        Connection connection = conexion.conectar();

        String usuario = txtUser2.getText();
        String nombre = txtNombre2.getText();
        String contraseña = txtContraseña2.getText();
        String ValidarContra = txtConfirmarContraseña2.getText();
        
        int vacio = usuario.length(); 
        int vacio2 = nombre.length();
        int vacio3 = contraseña.length();
        
        if (vacio != 0 && vacio2 != 0 && vacio3 !=0) {      
            if (contraseña.equals(ValidarContra)) {
                try {
                    String sql = "INSERT INTO `users`(`nombre`, `userName`, `password`) VALUES (?,?,?)";
                    PreparedStatement pstm = connection.prepareStatement(sql);

                    pstm.setString(1, nombre);
                    pstm.setString(2, usuario);
                    pstm.setString(3, contraseña);

                    pstm.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Su cuenta ha sido registrada correctamente :)");
                    dispose();
                    new frmLogin().setVisible(true);

                } catch (Exception e) {

                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            } else {

                JOptionPane.showMessageDialog(null, "Tus contraseñas no coinciden");

            }
        }else{
            JOptionPane.showMessageDialog(null, "Todavia te faltan campos por llenar");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnIniciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaActionPerformed
        new frmLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIniciaActionPerformed

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed
        new MenuPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInicia;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btnRegistrar2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtConfirmarContraseña2;
    private javax.swing.JTextField txtContraseña2;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtUser2;
    // End of variables declaration//GEN-END:variables
}
